### ISSUE TITLE
401 on refresh causes app to break

### ISSUE THREAD

**Issue by silver8ack** [websanova/vue-auth#155]
If I authenticate with my API, then close my browser or go to another page so that the refresh does not occur, upon revisting the app, it is broken because I have an expired token and the refresh method is failing.

I'm getting a 401 when trying to revisit my app after the token has expired.  I have been able to work around this by replacing the following on auth.js (line 74):
```             
success: function () {
    this.options.checkAuthenticated.call(_this, cb);
}
```
with this
```
success: function () {
    this.options.checkAuthenticated.call(_this, cb);
},
error: function () {
    window.localStorage.removeItem('default-auth-token');
}
```

I'm sure there is a more elegant solution, but I needed a quick fix.

**Comment by websanova** [comment]
Should be fixed in latest version

**Comment by ultraN** [comment]
This problem is not fixed, at least for me. #169 

Still doesn't handle error doing first refresh token.
