### ISSUE TITLE
oauth2 url improperly generated

### ISSUE THREAD

**Issue by jerzyk** [websanova/vue-auth#394]
https://github.com/websanova/vue-auth/blob/f0cdb93dfa5272b342053d1bb35cf19948400efa/src/auth.js#L467

this for-loop is creating a string starting with "&" (ampersand) which will generate final url in form:
http:/host/?&....

this is incorrect because strict parsing of the url (default setting on most of the servers) will find an empty parameter (yes - between '?' and '&')

additionally, values are not encoded, e.g. if you put redirectUrl as 'http://host/?smtg=1&smth2=2'

**Comment by websanova** [comment]
ok fixed in `2.21.12-beta`, thx :-)

**Comment by jerzyk** [comment]
`data.params[key]` is still not escaped, why not to wrap it with `encodeURIComponent`?

**Comment by websanova** [comment]
Yep, grab the latest `v2.21.13-beta` :-)
