### ISSUE TITLE
Error on browser refresh

### ISSUE THREAD

**Issue by lawrence615** [websanova/vue-auth#561]
Congrats on the work done in the lib. 

I have managed to setup the plugin and make it work and finally am able to login, fetch user, logout, fetch token, etc. 

However, I still have some few remaining issues;

1. When I refresh the browser it's like the app loses state even when `staySignedIn:true` is set. But the key is still available in local storage and I can see it.

```
    loginData: {
        url: 'auth/login',
        method: 'POST',
        redirect: '/',
        staySignedIn: true,
        rememberMe: true,
        fetchUser: true
    }
```

2. Token refresh is not happening automatically when there's a response of token expired.

Kindly advise. Thanks

**Comment by websanova** [comment]
you need to take a look at the `check` and `load` methods.

So basically if it's a user page, you need to hold the loading icon until the load finishes for auth.

https://websanova.com/docs/vue-auth/methods/examples#load

**Comment by lawrence615** [comment]
Thanks for the response;

This is how I have done it but still getting an issue when I refresh the browser;

```
this.$auth
      .load()
      .then(() => {
             if (this.$auth.check()) {
                  this.init(this.tableOptions)
              }
})
```
`init` is the function am calling to fetch data.

What happens on browser refresh, the app fetches the user again

**Comment by websanova** [comment]
I've updated the docs a bit here for reference:

https://websanova.com/docs/vue-auth/recipes/using-ready-and-load

But this should be fine, might depend what else you got going on in your app.

What happens if you do:

```
this.$auth
    .load()
    .then(() => {
        this.$auth.user();

        // if no user here, could be your issue.
    })
```

**Comment by lawrence615** [comment]
Still getting an error... when you refresh the browser the app tries to fetch a user and finds token is invalid then pings endpoint to refresh token.

<img width="582" alt="Screenshot 2020-05-21 at 09 45 35" src="https://user-images.githubusercontent.com/3224157/82531385-f72b1300-9b47-11ea-8670-67a24ec6b946.png">

I have commented any other part that has a http request apart from login;

```
this.$auth
      .login({
             data: vm.form.body,
             staySignedIn: true,
        })
        .then((res) => {
               vm.$auth.remember(this.$auth.user().name)
         }, (error) => {
              vm.showAlert('error', error.response.data.error)
         })
```

The login goes through well but app fails on browser refresh.

If I add your suggestion and refresh,  same error. Seems there's something triggering user request on browser refresh.

**Comment by lawrence615** [comment]
I have  narrowed down this issue to route auth meta value.

When `{auth: false}` is set, no issue when browser refreshes. 

```
            ...
            {
                path: 'dashboard',
                name: 'dashboard',
                component: loadView('Dashboard'),
                meta: {auth: false},
            },
```

But at the moment when you refresh a page twice which has `{auth: true}` set, you get the above error.

```
            ...
            {
                path: 'dashboard',
                name: 'dashboard',
                component: loadView('Dashboard'),
                meta: {auth: true},
            },
```

**Comment by websanova** [comment]
Well that seems like errors from your api not the library.

I mean, there is a 500 error on the refresh call...
